### ISSUE TITLE
IETF-116 Presentation

### ISSUE THREAD

**Issue by ggalimba56** [ggalimba56/draft-poidt-ccamp-actn-poi-pluggable#3]
Please have a look to the preso and provide feedbacks.

[IETF-116-draft-poidt-ccamp-actn-poi-pluggable.pptx](https://github.com/ggalimba56/draft-poidt-ccamp-actn-poi-pluggable/files/11048632/IETF-116-draft-poidt-ccamp-actn-poi-pluggable.pptx)

**Comment by italobusi** [comment]
Overall the slides look aligned with the discussion we have had

I have few comments/questions

1. Looking at point 4 in slide 2 ("Define a set of use cases to address and plan the Yang models extension to support them") and the penultimate bullet in slide 7 ("Define the (Yang) models to support the Pluggables in Routers"), I am getting the feeling that the future plan for this draft is to define YANG models to support these use cases, while my previous understanding was that this draft is mainly intended to identify the gaps and trigger further work in other drafts to resolve those gaps (as it has been done in the parent POI draft).

   Could you please clarify this point?

3. Looking at some supported use cases in slide 6 (Optical Restoration and Network Maintenance Operations) and the new use cases in slide 7, I am getting the feeling that this draft is going to cover also the service assurance aspects in case of pluggable optics, while my previous understanding (reported also in the slides to be presented at TEAS WG) was that this draft was only covering the same set of use cases of the parent draft and service assurance aspects for pluggable and grey interfaces are covered in the POI assurance draft.

   Could you please clarify this point?

5. Pending alignment on previous point, I would also suggest to copy slides 2 and 3 from the POI assurance presentation (https://github.com/italobusi/draft-poidt-teas-actn-poi-assurance/pull/6) to give a consistent view of the overall picture of these three drafts

6. In the third bullet of slide 7, I would mention terminology alignment also to other relevant IETF drafts or RFCs

**Comment by ggalimba56** [comment]
Hi Italo,

See in line [gmg]

I’ll update the preso.

Thanks a lot !

Best Regards,

Gabriele

From: italobusi ***@***.***>
Reply to: ggalimba56/draft-poidt-ccamp-actn-poi-pluggable ***@***.***>
Date: Thursday, 23 March 2023 at 10:39
To: ggalimba56/draft-poidt-ccamp-actn-poi-pluggable ***@***.***>
Cc: ggalimbe ***@***.***>, Author ***@***.***>
Subject: Re: [ggalimba56/draft-poidt-ccamp-actn-poi-pluggable] IETF-116 Presentation (Issue #3)


Overall the slides look aligned with the discussion we have had

I have few comments/questions

  1.  Looking at point 4 in slide 2 ("Define a set of use cases to address and plan the Yang models extension to support them") and the penultimate bullet in slide 7 ("Define the (Yang) models to support the Pluggables in Routers"), I am getting the feeling that the future plan for this draft is to define YANG models to support these use cases, while my previous understanding was that this draft is mainly intended to identify the gaps and trigger further work in other drafts to resolve those gaps (as it has been done in the parent POI draft).

Could you please clarify this point?   [gmg] yes you are right, I’ll rephrase the sentences to be more plear

  1.  Looking at some supported use cases in slide 6 (Optical Restoration and Network Maintenance Operations) and the new use cases in slide 7, I am getting the feeling that this draft is going to cover also the service assurance aspects in case of pluggable optics, while my previous understanding (reported also in the slides to be presented at TEAS WG) was that this draft was only covering the same set of use cases of the parent draft and service assurance aspects for pluggable and grey interfaces are covered in the POI assurance draft.

Could you please clarify this point?   [gmg] Restoration and maintenance operation (better to say coordinated-maintenance) are not assurance in my opinion although they benefit of assurance loke alarm and PM functions.

  1.  Pending alignment on previous point, I would also suggest to copy slides 2 and 3 from the POI assurance presentation (italobusi/draft-poidt-teas-actn-poi-assurance#6<https://github.com/italobusi/draft-poidt-teas-actn-poi-assurance/pull/6>) to give a consistent view of the overall picture of these three drafts   [gmg] OK !
  2.  In the third bullet of slide 7, I would mention terminology alignment also to other relevant IETF drafts or RFCs.  [gmg] agree, I move it to first position

**Comment by ggalimba56** [comment]
I’ve updated the slides upon Jeff, Italo, Sergio and Daniele comments.
[IETF-116-draft-poidt-ccamp-actn-poi-pluggable.pptx](https://github.com/ggalimba56/draft-poidt-ccamp-actn-poi-pluggable/files/11052467/IETF-116-draft-poidt-ccamp-actn-poi-pluggable.pptx)

**Comment by sergiobelotti** [comment]
> I’ve updated the slides upon Jeff, Italo, Sergio and Daniele comments. [IETF-116-draft-poidt-ccamp-actn-poi-pluggable.pptx](https://github.com/ggalimba56/draft-poidt-ccamp-actn-poi-pluggable/files/11052467/IETF-116-draft-poidt-ccamp-actn-poi-pluggable.pptx)

@ggalimba56  Thanks !
